# Generated by Django 2.2 on 2021-10-12 15:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('advertiser_management', '0003_auto_20211012_1902'),
    ]

    operations = [
        migrations.RenameField(
            model_name='click',
            old_name='ad_id',
            new_name='ad',
        ),
        migrations.RenameField(
            model_name='view',
            old_name='ad_id',
            new_name='ad',
        ),
    ]
