# Generated by Django 2.2 on 2021-10-24 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advertiser_management', '0006_counter'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='counter',
            name='click_cnt',
        ),
        migrations.RemoveField(
            model_name='counter',
            name='view_cnt',
        ),
        migrations.CreateModel(
            name='CounterValue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('click_cnt', models.IntegerField()),
                ('view_cnt', models.IntegerField()),
                ('advertiser', models.ManyToManyField(to='advertiser_management.Advertiser')),
            ],
        ),
    ]
