# Generated by Django 2.2 on 2021-10-24 08:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('advertiser_management', '0007_auto_20211024_1100'),
    ]

    operations = [
        migrations.AddField(
            model_name='countervalue',
            name='counter',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='advertiser_management.Counter'),
        ),
        migrations.RemoveField(
            model_name='countervalue',
            name='advertiser',
        ),
        migrations.AddField(
            model_name='countervalue',
            name='advertiser',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='advertiser_management.Advertiser'),
        ),
    ]
